version: '3.8'
services:
  har2postman:
    image: node:16-alpine
    container_name: har2postman
    working_dir: /app
    volumes:
      - ./:/app
    command: npm start
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
