version: '3.8'

services:
  har2postman:
    build: .
    container_name: har2postman
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3